### ISSUE TITLE
Build error when running `react-native run-android` in `:app:transformClassesWithDexForDebug`

### ISSUE THREAD

**Issue by jsfr** [joonhocho/react-native-google-sign-in#23]
After setting up the android side of the project and trying to run it I get the following error:

```
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb$1;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb$1;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to getmore log output.

BUILD FAILED
```

I can't figure out what is going wrong, any help would be greatly appreciated :)

**Comment by jsfr** [comment]
I seems to have been because I was using another react-native lib which also depended on some google services. Thus I had to exclude the services in the `android/app/build.gradle`

**Comment by mescalito** [comment]
@jsfr I'm having the same error, but I don't understand your solution, what do you mean by "using another react-native lib"? what lib? and how do you "exclude the services in the android/app/build.gradle"?

Thanks for your time!
